#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# get last argument of previous command with Alt-.
bindkey '\e.' insert-last-word
# prefix sudo with Control-a
bindkey -s "" 'sudo '
bindkey -s "" 'man '
set -k

alias ins="sudo apt-get install"
alias upd='sudo apt-get update'
alias upg='sudo apt-get upgrade'
alias renm='sudo service network-manager restart'
alias ..='cd ..'
alias ...='cd ../..'
alias cdd='cd ~/Desktop'
alias pyserve='python -m SimpleHTTPServer'
alias df='df -h'
alias iqt='ipython qtconsole --colors=linux'
alias hist='cat ~/.eternal_history | grep'
alias psef='ps -ef | grep'
alias vim='nvim'
alias gdb='gdb -q'

# OPAM configuration
. /home/harsh/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

export PATH=$PATH:/opt/framac/bin

function pantheon_command_completion {
  # Show notifications when a task is completed. (Pantheon-terminal)
  if [[ -n "$PANTHEON_TERMINAL_ID" ]] \
  && builtin hash dbus-send 2> /dev/null \
  && [[ -z $(whence pantheon_terminal_command_competion_callback) ]]
  then
  dbus-send \
      --type=method_call \
      --session \
      --dest=net.launchpad.pantheon-terminal \
      /net/launchpad/pantheon_terminal \
      org.pantheon.terminal.ProcessFinished \
      string:$PANTHEON_TERMINAL_ID \
      string:"$(fc -ln -1)"
  fi
}

add-zsh-hook precmd pantheon_command_completion
